language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install .

script: 
  - flake8 *.py kingman tests --exclude=ez_setup.py
  - nosetests --with-coverage --cover-package kingman
              --cover-inclusive --cover-min-percentage 85
  - make -C docs/source/ html
